kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: backend
  labels:
    component: mysql
    project: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: backend
      tier: backend
  template:
    metadata:
      labels:
        component: mysql
        project: backend
        tier: backend
    spec:
      containers:
      - name: mysql
        image: narendranreddy/mysql:v1.0 
